version: '2'
services:
  gdufs-admin:
    image: gdufs/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  gdufs-api:
    image: gdufs/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev